#!/usr/bin/python3
import os
import sys


class Gen:
    @staticmethod
    def file_to_yaml_multiline(file_path):
        file_text = os.popen(f"cat {file_path}").read()
        print(f'"{file_text}"')

    @staticmethod
    def generate_graphql_resolvers(*resolver_names):
        return


if __name__ == "__main__":
    func_name = sys.argv[1].replace("-", "_")
    args = sys.argv[2:] if len(sys.argv) > 2 else []
    getattr(Gen, func_name)(*args)
