AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  aw2-api

  AlgoWolf v2 copy trading application

Parameters:
  EnvironmentName:
    Type: String
  RepositoryBranch:
    Type: String

Conditions:
  IsProd: !Equals [!Ref EnvironmentName, aw2-prod]
  IsStage: !Equals [!Ref EnvironmentName, aw2-staging]

Resources:
  FrontendStack:
    Type: AWS::Serverless::Application
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      Location: stacks/frontend.yaml
      Parameters:
        EnvironmentName: !Sub ${EnvironmentName}

  UserApiStack:
    Type: AWS::Serverless::Application
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      Location: stacks/user-api.yaml
      Parameters:
        EnvironmentName: !Ref EnvironmentName
        ApiHostedZoneId: Z0434047RQEXFDWYFBU6

  TradeApiStack:
    Type: AWS::Serverless::Application
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      Location: stacks/trade-api.yaml
      Parameters:
        EnvironmentName: !Ref EnvironmentName

  ApiRecordSetGroupProd:
    Type: AWS::Route53::RecordSetGroup
    Condition: IsProd
    Properties:
      HostedZoneId: Z0434047RQEXFDWYFBU6
      RecordSets:
        - AliasTarget:
            DNSName: !Sub ${FrontendStack.Outputs.FrontendCloudFrontDistributionDomainName}
            EvaluateTargetHealth: false
            HostedZoneId: Z2FDTNDATAQYW2
          Name: www.ethanhollins.com
          Type: A
        - AliasTarget:
            DNSName: !Sub ${FrontendStack.Outputs.FrontendCloudFrontDistributionDomainName}
            EvaluateTargetHealth: false
            HostedZoneId: Z2FDTNDATAQYW2
          Name: ethanhollins.com
          Type: A
        - AliasTarget:
            DNSName: !Sub ${UserApiStack.Outputs.UserHttpApiDomainNameRegionalDomainName}
            EvaluateTargetHealth: true
            HostedZoneId: Z2RPCDW04V8134
          Name: !Sub ${UserApiStack.Outputs.UserHttpApiDomainName}
          Type: A

  ApiRecordSetGroupStage:
    Type: AWS::Route53::RecordSetGroup
    Condition: IsStage
    Properties:
      HostedZoneId: Z0434047RQEXFDWYFBU6
      RecordSets:
        - AliasTarget:
            DNSName: !Sub ${FrontendStack.Outputs.FrontendCloudFrontDistributionDomainName}
            EvaluateTargetHealth: false
            HostedZoneId: Z2FDTNDATAQYW2
          Name: sandbox.ethanhollins.com
          Type: A
        - AliasTarget:
            DNSName: !Sub ${UserApiStack.Outputs.UserHttpApiDomainNameRegionalDomainName}
            EvaluateTargetHealth: true
            HostedZoneId: Z2RPCDW04V8134
          Name: !Sub ${UserApiStack.Outputs.UserHttpApiDomainName}
          Type: A
