name: AW2 Api CI/CD

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint pytest
        pip install -r $(find ./* -name requirements.txt)
    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py')
    - name: Test code with pytest
      run: |
        pytest -c pytest.ini
    
  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: >
      github.ref == 'refs/heads/master' 
      || github.ref == 'refs/heads/production'
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"
    - name: Install python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install invoke
    - name: Install build dependencies
      run: |
        sudo apt-get install -y gpp
        sudo wget -qO /usr/local/bin/yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
        sudo chmod a+x /usr/local/bin/yq
    - uses: aws-actions/setup-sam@v2
    - uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-southeast-2
    - name: Build/Deploy AWS SAM
      run: |
        branch_name="${GITHUB_REF##*/}"
        echo "Deploying from ${branch_name} branch."
        if [[ ${branch_name} == "master" ]]; then
          invoke dev.deploy
        elif [[ ${branch_name} == "production" ]]; then
          invoke prod.deploy
        else
          printf '%s\n' "Unexpected branch name" >&2
          exit 1
        fi

